"""initial

Revision ID: 0016db48aed6
Revises: aa72f6b6680f
Create Date: 2024-04-24 17:27:16.126741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0016db48aed6'
down_revision: Union[str, None] = 'aa72f6b6680f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('payment_id', sa.UUID(), nullable=False))
    op.drop_constraint('user_subscriptions_service_payment_id_fkey', 'user_subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'user_subscriptions', 'payments', ['payment_id'], ['id'])
    op.drop_column('user_subscriptions', 'service_payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('service_payment_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_subscriptions', type_='foreignkey')
    op.create_foreign_key('user_subscriptions_service_payment_id_fkey', 'user_subscriptions', 'payments', ['service_payment_id'], ['id'])
    op.drop_column('user_subscriptions', 'payment_id')
    # ### end Alembic commands ###
