"""initial

Revision ID: 8b7fecba0297
Revises: f292046e6350
Create Date: 2024-04-24 16:53:12.625621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b7fecba0297'
down_revision: Union[str, None] = 'f292046e6350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('service_payment_id', sa.UUID(), nullable=False))
    op.drop_column('payments', 'payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('payments', 'service_payment_id')
    # ### end Alembic commands ###
