"""initial

Revision ID: 937ea9781c57
Revises: 580a1822ad1d
Create Date: 2024-04-24 14:47:58.438823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937ea9781c57'
down_revision: Union[str, None] = '580a1822ad1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('last_payment_id', sa.UUID(), nullable=False))
    op.drop_constraint('user_subscriptions_payment_id_fkey', 'user_subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'user_subscriptions', 'payments', ['last_payment_id'], ['id'])
    op.drop_column('user_subscriptions', 'payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_subscriptions', type_='foreignkey')
    op.create_foreign_key('user_subscriptions_payment_id_fkey', 'user_subscriptions', 'payments', ['payment_id'], ['id'])
    op.drop_column('user_subscriptions', 'last_payment_id')
    # ### end Alembic commands ###
